# Generated by Django 5.2.11 on 2026-03-16 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('half_paid', 'Half Payment Received'), ('paid', 'Fully Paid'), ('processing', 'Processing'), ('ready', 'Ready for Delivery/Pickup'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('defaulted', 'Payment Defaulted')], default='pending', max_length=20)),
                ('delivery_type', models.CharField(choices=[('home', 'Home Delivery'), ('pickup', 'In-Store Pickup')], max_length=10)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_on_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('full', 'Full Payment'), ('half', 'Half Payment')], default='full', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('variant_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_type', models.CharField(default='full', max_length=20)),
                ('upfront_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_on_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
